### PR TITLE
Updating pyproject.toml with valid python versions

### LINKED ISSUE #105: Indicate valid Python versions in pyproject.toml
After #103 , #104 

Once valid python versions have been identified - i.e. those that pass all tests for all platforms - the `pyproject.toml` file should be updated to indicate what are those valid python versions, so MUSE can be installed in them. In principle, this should be as simply as modifying the line with `requires-python` with the appropriate values.

### PR DESCRIPTION
**Pull request by TinyMarsh**
# Description

This PR addresses #105 updating the `pyproject.toml` file to include the Python versions which were included in the CI workflow in #119 . Specifically, the valid versions that MUSE can now be installed in are 3.8 and 3.9.

Closes #105 

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [x] All tests pass: `$ python -m pytest`
- [ ] The documentation builds and looks OK: `$ python setup.py build_sphinx`

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by dalonsoa** [comment]
This QA is facing but because of something to change in #118 , so nothing to do here until that is sorted. 

@jamesturner246 , let @TinyMarsh know when you're done with that one so he can rebase.

**Comment by jamesturner246** [comment]
@TinyMarsh @dalonsoa fixed in #118. Was just commas and whitespace fuss.

**Comment by TinyMarsh** [comment]
I prematurely rebased. It seems I should wait until #118 is merged before rebasing this branch.

**Comment by dalonsoa** [comment]
#118 Merged! All yours!

**Comment by TinyMarsh** [comment]
@dalonsoa Rebased and ready for review.

**Pull request merged**
