### PR TITLE
Doc links update

### PR DESCRIPTION
**Pull request by alexanderkell**
# Description

Updates the dead links in the documentation to the case studies with the `csv` files.

Fixes [# (issue)](https://github.com/SGIModel/MUSE_OS/issues/3)

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [ ] All tests pass: `$ python -m pytest`
- [x] The documentation builds and looks OK: `$ python setup.py build_sphinx`

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by alexanderkell** [comment]
This PR solves https://github.com/SGIModel/MUSE_OS/issues/7

**Review by sgiarols — COMMENTED** [review]
- overview.rst: foresight could be an inline figure
- installation routine to be updated
- technodata.rst has a few links not displayed properl(inputs-agents and existing_capacity)
- inputs_csv.rst has not updated links ('inputs/timeslices' ad 'inputs/regions')
- docs/add-solar file seems redundant
- API is not built

**Comment by alexanderkell** [comment]
Thanks @sgiarols. I have fixed:

- installation routine to be updated
- technodata.rst has a few links not displayed properl(inputs-agents and existing_capacity)
- inputs_csv.rst has not updated links ('inputs/timeslices' ad 'inputs/regions')
- docs/add-solar file seems redundant

Could you explain what you mean by "overview.rst: foresight could be an inline figure"? It looks okay to me on https://muse-docs.readthedocs.io/en/latest/overview.html#foresight-in-muse

Also for "API is not built" how are you building the docs? I am struggling to build it locally as I get the error below:
```
Running Sphinx v4.4.0

Extension error:
Could not import extension nbsphinx (exception: No module named 'nbsphinx')
make: *** [html] Error 2
```
Also, I am not sure how to view it online without connecting to readthedocs.

**Comment by alexanderkell** [comment]
@sgiarols, how do you view the documentation as built with GitHub actions? The API builds locally for me.

**Comment by sgiarols** [comment]
> @sgiarols, how do you view the documentation as built with GitHub actions? The API builds locally for me.

On readthedocs, the links are not working.

**Review by sgiarols — APPROVED** [review]

**Pull request merged**
